# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('batch_no', models.CharField(max_length=30)),
            ],
        ),
    ]
